// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCqfWQEnkDnlF9cTBfyd-1bhbh7egy88k',
    appId: '1:860489775317:web:3a6deef528ed7ea1918a5c',
    messagingSenderId: '860489775317',
    projectId: 'frtn-coaching-app',
    authDomain: 'frtn-coaching-app.firebaseapp.com',
    storageBucket: 'frtn-coaching-app.firebasestorage.app',
    measurementId: 'G-SG4BJGD06W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GXypbPWdDvSyAEPf6Llw2UexLng4c6M',
    appId: '1:860489775317:android:84a2e7f9e70a1aeb918a5c',
    messagingSenderId: '860489775317',
    projectId: 'frtn-coaching-app',
    storageBucket: 'frtn-coaching-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD84c7iB99SPJBtHE2ZuWycz6kan8_k4AU',
    appId: '1:860489775317:ios:2eedfff1ccd654cf918a5c',
    messagingSenderId: '860489775317',
    projectId: 'frtn-coaching-app',
    storageBucket: 'frtn-coaching-app.firebasestorage.app',
    iosBundleId: 'com.rody.frtncoachingapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD84c7iB99SPJBtHE2ZuWycz6kan8_k4AU',
    appId: '1:860489775317:ios:54a7c39ae8888198918a5c',
    messagingSenderId: '860489775317',
    projectId: 'frtn-coaching-app',
    storageBucket: 'frtn-coaching-app.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplicationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCqfWQEnkDnlF9cTBfyd-1bhbh7egy88k',
    appId: '1:860489775317:web:f28543aaba4eb081918a5c',
    messagingSenderId: '860489775317',
    projectId: 'frtn-coaching-app',
    authDomain: 'frtn-coaching-app.firebaseapp.com',
    storageBucket: 'frtn-coaching-app.firebasestorage.app',
    measurementId: 'G-T876JQGTNT',
  );
}
